# Generated by Django 5.2.12 on 2026-03-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_profile_address1_profile_address2_profile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='old_cart',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
