"""
Django settings for ecom project.

Generated by 'django-admin startproject' using Django 5.2.12.
"""
import os
from pathlib import Path
from django.templatetags.static import static

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-c&0zwhgtm8$!8ffin_jjmu#e1i3_xfmq*7#y#9x-^w$cilyg%6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition
INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'store',
    'cart',
    'payment'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ecom.urls'

# ==========================================
# ONE SINGLE TEMPLATES BLOCK (Fixed)
# ==========================================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'ecom' / 'templates'], # Corrected custom templates path
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processors.cart'  # <--- CRITICAL for the store to work
            ],
        },
    },
]

WSGI_APPLICATION = 'ecom.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    { 'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
MEDIA_URL='media/'
MEDIA_ROOT=os.path.join(BASE_DIR,"media")

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==========================================
# UNFOLD ADMIN THEME SETTINGS (With Navigation!)
# ==========================================
UNFOLD = {
    "SITE_TITLE": "Manank welcome",
    "SITE_HEADER": "Maccode Cart",
    "SITE_URL": "/",
    "DASHBOARD_CALLBACK": "ecom.dashboard.dashboard_callback",
    
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,  # Ensures your regular apps stay visible!
        
        # NEW: Custom navigation links with icons
        "navigation": [
            {
                "title": "Overview",
                "separator": True,
                "items": [
                    {
                        "title": "Dashboard",
                        "icon": "dashboard",
                        "link": "/admin/",
                    },
                    {
                        "title": "View Live Store",
                        "icon": "storefront",
                        "link": "/",
                    },
                ],
            },
        ],
    },
    
    "COLORS": {
        "primary": {
            "50": "#faf5ff", "100": "#f3e8ff", "200": "#e9d5ff",
            "300": "#d8b4fe", "400": "#c084fc", "500": "#a855f7",
            "600": "#9333ea", "700": "#7e22ce", "800": "#6b21a8",
            "900": "#581c87", "950": "#3b0764",
        },
        "base": {
            "50": "#f8fafc", "100": "#f1f5f9", "200": "#e2e8f0",
            "300": "#cbd5e1", "400": "#94a3b8", "500": "#64748b",
            "600": "#475569", "700": "#334155", "800": "#1e293b",
            "900": "#0f172a", "950": "#020617",
        },
    },
}
